### ISSUE TITLE
Notification package missing `RebootPopup` function

### ISSUE THREAD

**Issue by bamsammich** [google/cabbie#1]
I get the following error when building Cabbie:

```
# github.com/google/cabbie/cablib
..\..\..\go\src\github.com\google\cabbie\cablib\cablib.go:149:2: undefined: notification.RebootPopup
```

Indeed the `cablib` package does reference RebootPopup from `notification`, but `notification` does not have the corresponding function.

**Comment by cjgenevi** [comment]
fixed in commit [c948e2a](https://github.com/google/cabbie/commit/c948e2a0e2a29e7e62525bdb3c055494e1aa3956)
